[build-system]
requires = ["setuptools", "setuptools_scm[toml]"]
build-backend = "setuptools.build_meta"

[project]
name = "FBI"
dynamic = ["version"]
requires-python = ">=3.11"
dependencies = [
    "numpy < 2.3.0",
    "scipy",
    "ppigrf",
    "apexpy >= 2.1.1",
    "h5py",
    "matplotlib",
    "cartopy",
    "shapely",
    "geodarn @ git+https://github.com/RemingtonRohel/geodarn.git@main",
    # Vectorised gate2geographic_location(), until SuperDARN/pydarn#450 is merged
    "pydarn @ git+https://github.com/SuperDARN/pydarn@ehn/gate2geo_vectorisation",
    "lompe @ git+https://github.com/klaundal/lompe.git@main",
    "dipole @ git+https://github.com/klaundal/dipole.git@main#egg=dipole",
    "polplot @ git+https://github.com/klaundal/polplot.git@main#egg=polplot",
    "secsy @ git+https://github.com/klaundal/secsy.git@main#egg=secsy",
]

[project.optional-dependencies]
dev = [
    "pytest",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["FBI", "FBI.*"]
namespaces = false

[tool.setuptools_scm]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = ["-ra", "--showlocals", "--strict-markers", "--strict-config"]
xfail_strict = true
testpaths = [
    "tests",
]
